sudo: false
language: ruby
bundler_args: --without beaker
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
env:
  - PUPPET_GEM_VERSION="~> 3.7"
  - PUPPET_GEM_VERSION="~> 4.0"
matrix:
  exclude:
    - rvm: 2.2
      env: PUPPET_GEM_VERSION="~> 3.7"
    - rvm: '2.1'
      sudo: required
      services: docker
      env: BEAKER_set="fedora-23-docker"
      script: bundle exec rake acceptance
      bundler_args: --without development
    - rvm: '2.1'
      sudo: required
      services: docker
      env: BEAKER_set="ubuntu-14.04-docker"
      script: bundle exec rake acceptance
      bundler_args: --without development
  fast_finish: true
notifications:
  email: false
